Behaviour trees v2
AgustinZavalaA/RLP_TMR2023 pull request #12
Opened 2023-03-10 22:58 UTC by Yisuslalala

2023-03-10 23:07 UTC, AgustinZavalaA requested changes
Please fix the comments added and make sure to pass flake8 and mypy

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/mpu_controller/mpu_controller.py
> +class MpuController(metaclass=Singleton):
In this file Singleton is not imported

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/mpu_controller/mpu_controller.py
> +from abc import abstractclassmethod
You should change the name of this directory and file (do not include "controller") as this file is not already a controller, as it is not extending a Singleton or implementing a Mock and factory

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/mpu_controller/mpu_controller.py
> +    time.sleep(1)
Test if this code works

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +import enum
Make sure to pass flake8 and mypy as first step

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +class Distances(enum.Enum):
I think this enum is good, but it should be defined in another place, mark a TODO comment and is ok

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +class CanViewingToBB(py_trees.behaviour.Behaviour):
Mark a TODO comment to remove this class as it is only used for testing reasons

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +def create_can_distance() -> py_trees.behaviour.Behaviour:
rename this function to specify that it is a subtree

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +def can_distance(distance: Distances) -> py_trees.behaviour.Behaviour:
remove this function as I think with the enum it should not be necessary

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +        condition=lambda blackboard: condition_can(blackboard, Distances.CLOSE),
remove condition function as use only the lambda

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +        condition=lambda blackboard: condition_can(blackboard, Distances.FAR),
same as above

2023-03-10 23:07 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +        condition=lambda blackboard: condition_can(blackboard, Distances.GOOD),
same as above

2023-03-11 03:06 UTC, Yisuslalala commented on src/RLP_TMR2023/mpu_controller/mpu_controller.py
> +    time.sleep(1)
It works boss

2023-03-14 00:34 UTC, AgustinZavalaA requested changes

2023-03-14 00:34 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +class CanViewingToBB(py_trees.behaviour.Behaviour):
do this one

2023-03-14 00:34 UTC, AgustinZavalaA commented on src/RLP_TMR2023/prueba_behaviour_trees/can_distance.py
> +def create_can_distance() -> py_trees.behaviour.Behaviour:
and this one

2023-03-14 00:36 UTC, AgustinZavalaA approved these changes

2023-03-14 00:37 UTC, merged